//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caza.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CazaTuCasaEntities : DbContext
    {
        public CazaTuCasaEntities()
            : base("name=CazaTuCasaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DOCUMENTACION> DOCUMENTACION { get; set; }
        public DbSet<INMUEBLE> INMUEBLE { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<PUBLICACION> PUBLICACION { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
