//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLICACION
    {
        public PUBLICACION()
        {
            this.INMUEBLE = new HashSet<INMUEBLE>();
        }
    
        public int ID_PUBLICACION { get; set; }
        public Nullable<int> ID_INMUEBLE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<INMUEBLE> INMUEBLE { get; set; }
        public virtual INMUEBLE INMUEBLE1 { get; set; }
    }
}
