//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.INMUEBLE = new HashSet<INMUEBLE>();
        }
    
        public int ID_REGISTRO { get; set; }
        public string NOMBRE_REGISTRO { get; set; }
        public string APELLIDO_REGISTRO { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string DIRECCION { get; set; }
    
        public virtual ICollection<INMUEBLE> INMUEBLE { get; set; }
    }
}
